Repository SimonAlling/better-sweclockers, pull requests merged in 2020-11, with the labels that each got.

#148 Patch dark theme toggle
  src/config.ts
  src/icons/dark-theme-toggle.svg
  src/operations.ts
  src/operations/dark-theme.tsx
  src/site.ts
  src/stylesheets.ts
  src/stylesheets/dark-theme-toggle-preparations.scss
  src/stylesheets/dark-theme-toggle.scss
  src/text.ts
Labels: update

#149 Remove obsolete top menu tab code
  src/config.ts
  src/operations/logic/topMenuTab.tsx
  src/selectors.ts
  src/stylesheets/main.scss
Labels: code, update

#144 Add option to insert tab or spaces with Tab key
  src/actions.ts
  src/operations.ts
  src/operations/keyboard-shortcuts/edit-mode.ts
  src/preferences/edit-mode.ts
  src/preferences/keyboard.ts
  src/text.ts
Labels: feature

#150 Patch preferences shortcut again
  src/operations.ts
  src/operations/preferences-shortcut.ts
  src/operations/preferences-shortcut.tsx
  src/selectors.ts
  src/text.ts
Labels: update

#151 Fix editing tools preferences formatting
  src/config.ts
  src/operations/preferences-menu.tsx
  src/site.ts
  src/utilities.ts
Labels: update

#153 Patch preferences menu layout
  src/stylesheets/preferences.scss
Labels: update

#154 Simplify unsupported preference error handling
  src/preferences-menu.tsx
  src/stylesheets/preferences.scss
Labels: code

#155 Add preferences menu test
  __tests__/preferences.test.ts
  __tests__/svgTransformer.js
  babel.config.json
  jest.config.js
  package-lock.json
  package.json
  src/preferences-menu.tsx
Labels: meta

#156 Patch interests preference
  src/preferences-menu.tsx
  src/selectors.ts
  src/site.ts
Labels: update

#159 Patch bug where proofreading messes up headings
  src/operations.ts
  src/operations/proofreading.ts
Labels: bug

#160 Update/improve uninteresting subforums feature
  src/config.ts
  src/environment.ts
  src/operations.ts
  src/operations/uninteresting-subforums.ts
  src/site.ts
  src/stylesheets.ts
  src/stylesheets/interests-new-in-forum.ts
  src/stylesheets/uninteresting-subforums.scss
  src/text.ts
Labels: enhancement, update

#161 Don't ignore *.png in .gitignore
  .gitignore
Labels: meta

#162 Add uninteresting subforums screenshot
  docs/screenshots/uninteresting-subforums.png
Labels: documentation

#165 Remove thread status tooltips
  src/preferences/general.ts
  src/site.ts
  src/stylesheets.ts
  src/stylesheets/thread-status-tooltips-logic.ts
  src/stylesheets/thread-status-tooltips.scss
  src/text.ts
Labels: update

#166 Remove dark theme backup server option
  src/dark-theme.ts
  src/operations/dark-theme.tsx
  src/preferences/dark-theme.ts
  src/text.ts
Labels: enhancement

#167 Patch prevent accidental signout again
  src/environment.ts
  src/operations.ts
  src/operations/prevent-accidental-signout.ts
  src/site.ts
Labels: update

#169 Improve user ID code
  src/operations/pm-links.tsx
  src/operations/prevent-accidental-signout.ts
  src/site.ts
Labels: code

#170 Patch PM links
  src/selectors.ts
  src/site.ts
  src/text.ts
Labels: update

#168 Update Soitora's dark theme stylesheet URL
  src/dark-theme.ts
Labels: dependencies

#173 Patch quote signature buttons
  src/operations/quote-signature-buttons.tsx
  src/site.ts
  src/stylesheets/main.scss
Labels: update

#174 Fix quote signature buttons (rounded corners)
  src/operations/quote-signature-buttons.tsx
  src/site.ts
  src/stylesheets/main.scss
Labels: bug

#175 Patch improved built-in editing tools (URL button)
  src/operations/improved-builtin-editing-tools-url.ts
Labels: update

#176 Improve editing tools label/tooltip naming
  src/operations/editing-tools.tsx
  src/operations/logic/editing-tools.tsx
  src/text.ts
Labels: code

#177 Improve preferences meta text naming
  src/operations/preferences-menu.tsx
  src/operations/preferences-shortcut.tsx
  src/preferences-menu.tsx
  src/preferences/advanced.ts
  src/preferences/dark-theme.ts
  src/preferences/edit-mode.ts
  src/preferences/editing-tools.ts
  src/preferences/general.ts
  src/preferences/interests.ts
  src/preferences/keyboard.ts
  src/text.ts
Labels: code

#178 Patch link to top
  src/config.ts
  src/operations.ts
  src/operations/link-to-top.ts
  src/operations/link-to-top.tsx
  src/selectors.ts
  src/stylesheets/main.scss
  src/text.ts
Labels: enhancement, update

#180 Use Europe/Stockholm time zone in CI
  .github/workflows/ci.yaml
  .github/workflows/validation.yaml
Labels: meta

#179 Keep logo in repo instead of SweClockers' CDN
  README.md
  docs/logo.png
  src/config.ts
Labels: code

#181 Incorporate better-sweclockers-lib
  package-lock.json
  package.json
  src/lib/proofreading/classes.ts
  src/lib/proofreading/index.ts
  src/lib/proofreading/style.scss
  src/lib/textarea.ts
  src/operations/proofreading.ts
  src/stylesheets.ts
  src/stylesheets/main.scss
  webpack.config.ts
Labels: code, dependencies

#182 Fix proofreading mistake highlighting
  src/lib/proofreading/style.scss
Labels: bug

#183 Don't perform proofreading if it's disabled
  src/operations.ts
Labels: bug

#184 Patch highlight own posts
  src/stylesheets/highlight-own-posts.scss
  src/text.ts
Labels: update

#185 Improve quote signature button tooltips
  src/operations/quote-signature-buttons.tsx
  src/stylesheets/main.scss
  src/text.ts
Labels: enhancement

#186 Upgrade to TypeScript 4 and Preact 10
  .eslintrc.yml
  package-lock.json
  package.json
  src/operations/autosave-draft.ts
  src/operations/dark-theme.tsx
  src/operations/editing-tools.tsx
  src/operations/heading-toolbar-button.tsx
  src/operations/link-to-top.tsx
  src/operations/logic/editing-tools.tsx
  src/operations/logic/render.ts
  src/operations/mention-everyone.tsx
  src/operations/pm-links.tsx
  src/operations/preferences-link.tsx
  src/operations/preferences-menu.tsx
  src/operations/preferences-shortcut.tsx
  src/operations/quote-signature-buttons.tsx
  src/operations/table-toolbar-button.tsx
  src/operations/textarea-size-toggle.tsx
  src/operations/web-search-button.tsx
  src/preferences-menu.tsx
  src/preferences/editing-tools.ts
  src/utilities.ts
  tsconfig.json
Labels: code, dependencies

#188 Clean up ESLint config
  .eslintrc.yml
Labels: code

#189 Add developer mode
  src/config.ts
  src/main.ts
  src/operations/developer-mode.tsx
  src/preferences/advanced.ts
  src/stylesheets.ts
  src/stylesheets/developer-mode.scss
  src/text.ts
Labels: feature

#190 Remove web search button
  src/operations.ts
  src/operations/editing-tools.tsx
  src/operations/logic/editing-tools.tsx
  src/operations/web-search-button.tsx
  src/preferences/editing-tools.ts
  src/preferences/general.ts
  src/search-engines.ts
  src/selectors.ts
  src/stylesheets.ts
  src/stylesheets/web-search-button.scss
  src/text.ts
Labels: update

#191 Fix replace followed threads link condition
  src/operations.ts
Labels: bug

#192 Patch autosave draft (obsolete draft deletion)
  src/selectors.ts
Labels: update

#193 Fix replace followed threads link content jumping
  src/stylesheets/replace-followed-threads-link.scss
Labels: bug

#194 Patch mention everyone
  src/operations/mention-everyone.tsx
Labels: update

#195 Fix forum thread detection
  src/environment.ts
  src/operations.ts
Labels: bug

#196 Fix pref. shortcut and dark theme toggle on mobile
  src/operations.ts
  src/site.ts
  src/stylesheets.ts
  src/stylesheets/dark-theme-toggle-preparations.scss
  src/stylesheets/dark-theme-toggle.scss
  src/stylesheets/preferences-shortcut.scss
Labels: enhancement
