Repository SimonAlling/better-sweclockers, pull requests merged in 2020-07, with the labels that each got.

#71 Clean up adaptive width
  src/stylesheets/adaptive-width.scss
Labels: update

#82 Add smileys in editing tools
  src/config.ts
  src/operations/editing-tools.tsx
  src/operations/logic/editing-tools.tsx
  src/operations/logic/smileys.ts
  src/preferences/editing-tools.ts
  src/site.ts
  src/stylesheets/editing-tools.scss
  src/text.ts
Labels: feature

#83 Enable autosave draft for PMs
  src/environment.ts
  src/operations.ts
  src/site.ts
Labels: enhancement

#87 Add links to dark theme forum threads
  src/dark-theme.ts
  src/preferences/dark-theme.ts
  src/text.ts
Labels: enhancement

#88 Fix layout issues in preferences menu
  src/config.ts
  src/stylesheets/editing-tools.scss
Labels: bug

#92 Fix Nightly @downloadURL and @updateURL
  .github/workflows/nightly.yaml
Labels: bug

#90 Update Sweclockers Dark to use 3.X
  src/dark-theme.ts
Labels: enhancement

#97 Add undo support for our editing tools
  __tests__/browser.test.ts
  __tests__/utilities.ts
  docs/dialogs.md
  jest.config.js
  package-lock.json
  package.json
  src/browser.ts
  src/operations.ts
  src/operations/autosave-draft.ts
  src/operations/editing-tools.tsx
  src/operations/heading-toolbar-button.tsx
  src/operations/logic/editing-tools.tsx
  src/operations/logic/textarea.ts
  src/operations/table-toolbar-button.tsx
  src/operations/web-search-button.tsx
  src/preferences-menu.tsx
  src/preferences/advanced.ts
  src/preferences/editing-tools.ts
  src/text.ts
Labels: enhancement

#102 Add confirmation before applying shibe formatting
  src/operations/logic/editing-tools.tsx
  src/text.ts
Labels: enhancement

#103 Restore draft without confirmation with undo support
  src/operations/autosave-draft.ts
Labels: enhancement

#104 Move shibe code to its own module
  src/operations/actions/shibe.ts
  src/operations/logic/editing-tools.tsx
Labels: code

#105 Move NBSPs code to its own module
  src/operations/actions/replace-spaces-with-nbsps.ts
  src/operations/logic/editing-tools.tsx
Labels: code

#107 Move search link code to its own module
  src/operations/actions/search-link.ts
  src/operations/logic/editing-tools.tsx
Labels: code

#109 Add no-duplicate-imports lint rule
  .eslintrc.yml
Labels: code

#110 Update preferences menu operation comments
  src/operations.ts
Labels: code

#111 Simplify withMaybe
  package-lock.json
  package.json
  src/utilities.ts
Labels: code

#112 Improve split quote existing newlines extraction
  src/operations/actions/split-quote.ts
Labels: code

#113 Add semi (semicolons) lint rule
  .eslintrc.yml
  src/operations.ts
  src/operations/actions/replace-spaces-with-nbsps.ts
  src/operations/actions/search-link.ts
  src/operations/autosave-draft.ts
  src/operations/caret-position.ts
  src/operations/draft-mode-toggle.ts
  src/operations/editing-tools.tsx
  src/operations/heading-toolbar-button.tsx
  src/operations/improved-corrections.ts
  src/operations/link-to-top.ts
  src/operations/mention-everyone.tsx
  src/operations/mousetrap-preparations.ts
  src/operations/pm-links.tsx
  src/operations/preferences-link.tsx
  src/operations/preferences-menu.tsx
  src/operations/preferences-shortcut.tsx
  src/operations/prevent-accidental-signout.ts
  src/operations/prevent-accidental-unload.ts
  src/operations/proofreading.ts
  src/operations/quote-signature-buttons.tsx
  src/operations/remember-location-in-market.ts
  src/operations/remove-mobile-site-disclaimer.ts
  src/operations/replace-followed-threads-link.ts
  src/operations/table-toolbar-button.tsx
  src/operations/textarea-size-toggle.tsx
  src/operations/web-search-button.tsx
  src/preferences-menu.tsx
  src/stylesheets.ts
Labels: code

#114 Add import/order lint rule
  .eslintrc.yml
  metadata.ts
  package-lock.json
  package.json
  src/operations/editing-tools.tsx
  src/operations/logic/editing-tools.tsx
  src/stylesheets.ts
  webpack.config.ts
Labels: code

#115 Suppress eslint-plugin-react version warning
  .eslintrc.yml
Labels: code

#116 Add indent (indentation) lint rule
  .eslintrc.yml
  metadata.ts
  src/operations/autosave-draft.ts
  src/operations/logic/textarea.ts
  src/operations/pm-links.tsx
  src/operations/proofreading.ts
  src/operations/textarea-size-toggle.tsx
  src/preferences-menu.tsx
  src/stylesheets/hide.ts
  src/stylesheets/interests-new-in-forum.ts
  src/stylesheets/thread-status-tooltips-logic.ts
  src/time.ts
Labels: code

#117 Sort lint rules alphabetically
  .eslintrc.yml
Labels: code

#118 Add a few basic (already met) lint rules
  .eslintrc.yml
Labels: code

#119 Add improved built-in editing tools
  docs/builtin-editing-tools.md
  src/operations.ts
  src/operations/actions/shibe.ts
  src/operations/improved-builtin-editing-tools-url.ts
  src/operations/improved-builtin-editing-tools.ts
  src/operations/logic/textarea.ts
  src/preferences/edit-mode.ts
  src/text.ts
Labels: feature

#120 Fix PM links condition
  src/operations.ts
Labels: bug

#122 Use CI instead of nightly builds
  .github/workflows/ci.yaml
  .github/workflows/validation.yaml
Labels: meta

#123 Update/simplify prevent accidental signout
  src/operations/prevent-accidental-signout.ts
  src/site.ts
  src/text.ts
Labels: update
